# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-06 16:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0041_add_challenge_phase_max_submissions_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='allowed_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=['zip', 'json'], size=None),
        ),
    ]
